name: Release macOS App (.dmg)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Application and Generate .dmg
        run: |
          chmod +x ./create_dmg.sh
          ./create_dmg.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Project-Nobel-Installer.dmg
          generate_release_notes: true
          draft: false
          prerelease: false
